### ISSUE TITLE
Wallet Balance - Sensor Needed 

### ISSUE THREAD

**Issue by jonathanicq** [alexbelgium/hassio-addons-test#2]
Hi @alexbelgium 
I believe that would be great if you setup a sensor to show the actual value of the wallet
Doesn't need to be fancy, just something that sum up all the crypto and it's balance in EUR.

If you want to do an upgrade, you could do EUR and USD.

I created this as another thread, because would be easy to track it.

**Comment by alexbelgium** [comment]
That would be great, but I'm not the developer of the binance bot... Only of the integration. I don't have the knowledge or time to create such an integration...

**Comment by alexbelgium** [comment]
@jonathanicq hi, did you manage to use the other bot? Is it financially interesting? Thanks!

**Comment by jonathanicq** [comment]
@alexbelgium 
Now I found it LOL
I'm closing this ticket
